### ISSUE TITLE
training problem - PSNR converges at about 13

### ISSUE THREAD

**Issue by AddASecond** [princeton-computational-imaging/neural-scene-graphs#12]
hi, great work!
During training, I find that for several scenes such as scene 3,4,7, their PSNR can only achieve about 13. 
If use pretrained examples_6, the  PSNR of Scene6 can achieve about 21(still lower than 23 in the paper)
![origin_img_v2_ae3d4b6c-c9c0-4de7-a9a7-1111d61690eg](https://user-images.githubusercontent.com/12587374/184335398-56361cad-e0f5-4dd7-b4e6-befd329f2a2d.jpg)
I wonder what is the reason? Are there any training tricks?
Below is my conifg of Scene7, which is modefied from examples of Scene6:
[config_kitti_0007_example_train.txt](https://github.com/princeton-computational-imaging/neural-scene-graphs/files/9315595/config_kitti_0007_example_train.txt)

Looking forward to your reply Thanks

**Comment by ostjul** [comment]
Thank you! As stated in the paper the provided code and experiments just allow for minimal movement of the ego vehicle/camera due to the multi-plane background model. As far as I can see from the provided config file and images of scene 7 it involves a lot of ego movement. The multi-plane model of the background does not support this. You might be able to achieve better results by switching to a NeRF++ style background model and required scaling. I hope that is a solution to the problem!
